# baseURL = 'https://example.org/'
DefaultContentLanguage = "en"
languageCode = 'en-us'
title = 'Pertti Hallikainen'
theme = 'beautifulhugo'
summaryLength = 0


[Params]
  homeTitle = "Notes & Reviews" # Set a different text for the header on the home page
  subtitle = "Games, TV, technology etc"
  mainSections = ["post","posts"]
  logo = "img/SelfPortrait01.png" # Expecting square dimensions
  favicon = "img/favicon.ico"
  #dateFormat = "January 2, 2006"
  commit = false
  rss = false
#  comments = true
  readingTime = false
  wordCount = false
  useHLJS = false # something to do with syntax highlighting
  socialShare = false
  delayDisqus = true
#  showRelatedPosts = true
  hideAuthor = true


# workaround for https://github.com/halogenica/beautifulhugo/issues/480


defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true

[languages]
  [languages.en] 
    contentDir = "content/en" # English
    languageName = 'EN 🇬🇧'
    weight = 1


  [languages.fi]
    contentDir = "content/fi" # Suomi
    languageCode = 'fi-FI'
    languageName = 'FI 🇫🇮'
    weight = 2
    
    #title = 'otsikko suomeksi'
    
    [languages.fi.params]
      homeTitle = 'Kirjoituksia'
      subtitle = ''
      #dateFormat = "1.2.2006"



[Author]
  # full list of supported socials: https://github.com/halogenica/beautifulhugo/blob/master/data/beautifulhugo/social.toml
  # Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
  name = "Pertti Hallikainen"
  # website = "yourwebsite.com"
  email = "pertti.hallikainen@outlook.com"
  # facebook = "username"
  github = "pertti-hallikainen"
  twitter = "Prtthllknn"
  linkedin = "pertti-hallikainen-33b1a210b"



  [[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

  [[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 10

  [[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 20



